[project]
name = "1st-project"
version = "0.1.0"
description = "scraping ufc stats data and creating a ETL pipeline using uv, and a postgres docker container"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "requests>=2.32.5",
]
